name: Nightly Automation

on:

  schedule:
    - cron: "0 1 * * *"

jobs:

  nightly:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - run: |
          pytest tests/ \
          --alluredir=reports/allure-results \
          --html=reports/nightly.html \
          --self-contained-html
        env:
          PORTAL_ADMIN_BASE_URL: ${{ vars.PORTAL_ADMIN_BASE_URL }}
