name: Smoke Tests

on:
  workflow_dispatch:

jobs:

  smoke:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt

      - run: python -m playwright install --with-deps chromium

      - run: |
          xvfb-run --auto-servernum pytest tests/admin/smoke tests/user/smoke \
          --alluredir=reports/allure-results
        env:
          PLAYWRIGHT_HEADLESS: "false"
          PORTAL_ADMIN_BASE_URL: ${{ vars.PORTAL_ADMIN_BASE_URL }}
